import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs/promises';

const client = new Anthropic();

const DOC_TYPES = [
  'Passport', 'Emirates ID', 'Driving Licence', 'ID Document', 'Residence Visa', 'Marriage Certificate',
  'Bank Application', 'Bank Statement', 'Bank Statement Consent', 'Pay Slip', 'Salary Certificate', 'Salary Transfer Letter', 'P60', 'P45', 'SA302', 'Mortgage Statement',
  'Employment Letter', 'NOC Letter', 'Accountant Letter', 'Reference Letter', 'Trade License',
  'Title Deed', 'Tenancy Contract', 'Utility Bill', 'Council Tax',
];

const SYSTEM_PROMPT = `You are a document analysis assistant for a UK mortgage brokerage.
Analyse the document and return a JSON object with exactly five fields:

- "docType": choose the closest match from this list: ${DOC_TYPES.join(', ')}. If none match, use a short descriptive label.
  CRITICAL distinctions — read carefully:

  SALARY CERTIFICATE (classify as "Salary Certificate"):
  • A formal letter on company letterhead addressed to a bank or "To Whom It May Concern"
  • Uses phrases like "This is to certify", "We confirm that", "employed with us", "monthly salary of"
  • Lists basic salary + allowances as a summary — NO earnings/deductions table
  • Signed by HR manager or authorised signatory, often with a company stamp
  • Common in UAE/Middle East employment contexts
  • EVEN IF it mentions salary figures or allowances, if it is letter-format → "Salary Certificate"

  PAY SLIP (classify as "Pay Slip"):
  • A payroll stub or paycheck document, NOT a letter
  • Has a structured table showing gross pay, individual deductions (tax, NI, pension), and net pay
  • Covers a specific pay period (e.g. "August 2025")
  • Typically generated by payroll software (rows and columns of figures)

  RULE: If the document looks like a letter → "Salary Certificate". If it looks like a payroll table/stub → "Pay Slip". Never classify a letter as a Pay Slip.

  • "Bank Statement Consent" = a consent, mandate or authorisation form. Do NOT classify as "Bank Statement".
  • "Bank Application" = a loan or bank account application form. Do NOT classify as "Bank Statement".

- "personName": the full name of the primary person the document belongs to.
  Key rules:
  • Emirates ID: use the English name exactly as printed in the Name field — ignore all Arabic text.
  • Passport: use the name from the personal details page or MRZ (Given Names + Surname).
  • Residence Visa: use the visa holder's full English name.
  • Salary Certificate / Pay Slip: use the employee's name.
  • Bank Statement: use the account holder's name.
  Return null if you cannot determine a name.

- "period": for Bank Statement or Pay Slip only — a human-readable period string e.g. "Jan 2025" or "Jan 2025 - Mar 2025". Return null for all other document types.

- "periodStart": for Bank Statement or Pay Slip only — the start date in "YYYY-MM" format. Return null for all other document types.

- "periodEnd": for Bank Statement or Pay Slip only — the end date in "YYYY-MM" format (same as periodStart for single-month documents). Return null for all other document types.

Return ONLY valid JSON, no markdown, no explanation.`;

export async function analyzeDocument(filePath, mimeType) {
  const buffer = await fs.readFile(filePath);
  const base64 = buffer.toString('base64');

  const contentBlock = mimeType === 'application/pdf'
    ? { type: 'document', source: { type: 'base64', media_type: 'application/pdf', data: base64 } }
    : { type: 'image',    source: { type: 'base64', media_type: mimeType,           data: base64 } };

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 512,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: [contentBlock, { type: 'text', text: 'Analyse this document.' }] }],
  });

  const raw = message.content[0].text.trim();
  const json = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
  const result = JSON.parse(json);

  return {
    docType:     result.docType     || 'Unknown',
    personName:  result.personName  || '',
    period:      result.period      ?? null,
    periodStart: result.periodStart ?? null,
    periodEnd:   result.periodEnd   ?? null,
  };
}
